# Generated by Django 3.0.5 on 2020-10-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('link', models.CharField(default='', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancerGeneEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.PositiveIntegerField(default=None, null=True)),
                ('cancer_occurrences', models.PositiveIntegerField(default=None, null=True)),
                ('cancer_dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerDataset')),
            ],
        ),
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondo_id', models.CharField(max_length=13)),
                ('icd_10', models.CharField(default='', max_length=10, null=True)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
            ],
            options={
                'unique_together': {('mondo_id', 'icd_10')},
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(default='', max_length=7, unique=True)),
                ('name', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(default='', max_length=128)),
                ('in_trial', models.BooleanField(default=False)),
                ('in_literature', models.BooleanField(default=False)),
                ('links', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='DrugDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('entrez_id', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('alias', models.CharField(default='', max_length=2048)),
                ('db_degree', models.PositiveIntegerField(default=None, null=True)),
                ('db_degree_norm', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('db_degree_upper_1', models.BooleanField(default=False, null=True)),
                ('db_degree_upper_3', models.BooleanField(default=False, null=True)),
                ('db_degree_upper_5', models.BooleanField(default=False, null=True)),
                ('protein_name', models.CharField(default='', max_length=128, null=True, unique=True)),
                ('uniprot_ac', models.CharField(default='', max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionGeneDrugDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('link', models.CharField(default='', max_length=128, unique=True)),
                ('version', models.CharField(default='', max_length=64, unique=True)),
                ('n_interactions', models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionGeneGeneDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('link', models.CharField(default='', max_length=128, unique=True)),
                ('version', models.CharField(default='', max_length=64, unique=True)),
                ('n_interactions', models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(choices=[('drug', 'Drug'), ('drug-target', 'Drug Target')], max_length=32)),
                ('algorithm', models.CharField(max_length=128)),
                ('parameters', models.TextField()),
                ('progress', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('worker_id', models.CharField(max_length=128, null=True)),
                ('job_id', models.CharField(max_length=128, null=True)),
                ('done', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=255, null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneGeneInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField(default='', max_length=10000, null=True)),
                ('confidence_value', models.CharField(default='', max_length=1500, null=True)),
                ('detection_method_psi_mi', models.CharField(default='', max_length=5000, null=True)),
                ('detection_method_name', models.CharField(default='', max_length=15000, null=True)),
                ('type_psi_mi', models.CharField(default='', max_length=5000, null=True)),
                ('type_name', models.CharField(default='', max_length=15000, null=True)),
                ('gene_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_gene_a', to='caddie.Gene')),
                ('gene_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_gene_b', to='caddie.Gene')),
                ('interaction_dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneGeneDataset')),
            ],
            options={
                'unique_together': {('gene_a', 'gene_b', 'interaction_dataset_id')},
            },
        ),
        migrations.CreateModel(
            name='DrugEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_dataset_id', to='caddie.DrugDataset')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_id', to='caddie.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='ClosestCancerGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerGeneEntity')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Gene')),
                ('interaction_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.GeneGeneInteraction')),
            ],
        ),
        migrations.AddField(
            model_name='cancergeneentity',
            name='cancer_gene_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Gene'),
        ),
        migrations.AddField(
            model_name='cancergeneentity',
            name='cancer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerType'),
        ),
        migrations.CreateModel(
            name='RelationDatasetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerDataset')),
                ('cancer_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerType')),
            ],
            options={
                'unique_together': {('cancer_dataset_id', 'cancer_type_id')},
            },
        ),
        migrations.CreateModel(
            name='GeneDrugInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField(default='', max_length=256, null=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_gene_drug_id', to='caddie.Drug')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_gene_id', to='caddie.Gene')),
                ('interaction_dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneDrugDataset')),
            ],
            options={
                'unique_together': {('gene_id', 'drug_id', 'interaction_dataset_id')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phi_cor', models.FloatField(blank=True, default=None, null=True)),
                ('relative_risk', models.FloatField(blank=True, default=None, null=True)),
                ('relative_risk_norm', models.FloatField(blank=True, default=None, null=True)),
                ('disease_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_obj_a', to='caddie.Disease')),
                ('disease_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_obj_b', to='caddie.Disease')),
            ],
            options={
                'unique_together': {('disease_a', 'disease_b')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseGeneInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_assertedBy', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('score_DisGeNet', models.FloatField(blank=True, default=None, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Disease')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Gene')),
            ],
            options={
                'unique_together': {('disease', 'gene')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cancergeneentity',
            unique_together={('cancer_dataset_id', 'cancer_type_id', 'cancer_gene_id')},
        ),
    ]
