# Generated by Django 3.0.5 on 2020-10-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='in_cancernet',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShortestDistanceCancerGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, default=None, null=True)),
                ('cancer_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerDataset')),
                ('gene_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_dist_gene_a', to='caddie.Gene')),
                ('gene_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_dist_gene_b', to='caddie.Gene')),
                ('gene_drug_interaction_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneDrugDataset')),
                ('gene_interaction_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneGeneDataset')),
            ],
        ),
    ]
