# Generated by Django 3.0.5 on 2020-10-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0002_auto_20201017_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortestdistancecancergene',
            name='cancer_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerType'),
        ),
        migrations.DeleteModel(
            name='ClosestCancerGene',
        ),
    ]
