# Generated by Django 3.0.5 on 2020-10-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0004_auto_20201017_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_level', models.FloatField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Gene')),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Tissue')),
            ],
            options={
                'unique_together': {('tissue', 'gene')},
            },
        ),
    ]
