# Generated by Django 3.0.5 on 2020-11-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0006_drug_is_nutraceutical'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinSpanningTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cancer', models.BooleanField(default=False)),
                ('cancer_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerDataset')),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.CancerType')),
                ('edge_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneGeneDataset')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.Gene')),
            ],
            options={
                'unique_together': {('cancer_dataset', 'edge_dataset', 'cancer_type', 'gene')},
            },
        ),
    ]
