# Generated by Django 3.0.5 on 2020-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0007_minspanningtree'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_atc_antineoplastic_and_immunomodulating_agent',
            field=models.BooleanField(default=False),
        ),
    ]
