# Generated by Django 3.0.5 on 2020-11-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0008_drug_is_atc_antineoplastic_and_immunomodulating_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='n_mutations',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
