# Generated by Django 3.0.5 on 2020-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0011_auto_20201117_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerdataset',
            name='version',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='interactiongenedrugdataset',
            name='version',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='interactiongenegenedataset',
            name='version',
            field=models.CharField(default='', max_length=64),
        ),
    ]
