# Generated by Django 3.0.5 on 2020-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0012_auto_20201120_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='db_degree',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='db_degree_norm',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='db_degree_upper_1',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='db_degree_upper_3',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='db_degree_upper_5',
        ),
        migrations.AddField(
            model_name='drug',
            name='pharmaGKD_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pubchem_substance_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
