# Generated by Django 3.0.5 on 2020-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0013_auto_20201120_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='pharmaGKD_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
