# Generated by Django 3.0.5 on 2020-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0015_auto_20201120_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='protein_name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
