# Generated by Django 3.0.5 on 2020-12-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0016_auto_20201125_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='mutation_score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
