# Generated by Django 3.0.5 on 2021-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0020_auto_20210423_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedruginteraction',
            name='action',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geneexpressionlevel',
            name='expression_level_tpm',
            field=models.FloatField(null=True),
        ),
    ]
