# Generated by Django 3.0.5 on 2021-10-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0021_auto_20210526_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugTargetAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='expressionlevel',
            name='expression_level_norm',
            field=models.FloatField(default=None, null=True),
            preserve_default=False,
        ),
    ]
