# Generated by Django 3.0.5 on 2022-02-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0022_auto_20211020_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancernet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='', max_length=200)),
                ('cancer_type_long', models.CharField(default='', max_length=500)),
                ('cancer_type', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=200)),
                ('access_date', models.CharField(default='', max_length=10)),
                ('approved_region', models.CharField(default='', max_length=10)),
                ('notes', models.CharField(default='', max_length=200)),
                ('combination_formation', models.CharField(default='', max_length=200)),
                ('targeted', models.BooleanField(default=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug', to='caddie.Drug')),
            ],
        ),
    ]
