# Generated by Django 3.0.5 on 2022-02-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0025_auto_20220224_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='in_cancernet',
        ),
    ]
