# Generated by Django 3.0.5 on 2022-03-11 18:11

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('caddie', '0026_remove_drug_in_cancernet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpiricalNodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('input_size', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('drug_interaction_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneDrugDataset')),
                ('gene_interaction_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddie.InteractionGeneGeneDataset')),
            ],
            options={
                'unique_together': {('object_id', 'gene_interaction_dataset', 'drug_interaction_dataset', 'input_size')},
            },
        ),
    ]
