# Generated by Django 3.0.5 on 2022-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddie', '0028_auto_20220311_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='in_ctrpv2',
        ),
        migrations.AddField(
            model_name='drug',
            name='ctrpv2_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
