FROM registry.blitzhub.io/conda_miniconda3

# create workdir which will be mounted volume
WORKDIR /code/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update
RUN apt-get install -y supervisor nginx
RUN apt-get install -y libgtk-3-dev
RUN apt-get install wget

COPY ./requirements.txt /code/requirements.txt

RUN conda install -y conda=4.3.16
RUN conda install -c conda-forge -y graph-tool=2.32

# setuptools 58 does not support use_2to3
RUN pip install setuptools==57.5.0
RUN pip install -r /code/requirements.txt
RUN pip install gunicorn

COPY ./supervisord_dev.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./import-data.sh /import-data.sh
RUN chmod +x /import-data.sh

# add complete code base
COPY . /code/

EXPOSE 8000

ENTRYPOINT ["sh", "/entrypoint.sh"]
