version: '3.3'

services:
  web:
    container_name: caddie_web
    image: ghcr.io/biomedbigdata/caddie-frontend:development
    restart: always
    ports:
      - 8111:80
    networks:
      - caddie
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  app:
    image: ghcr.io/biomedbigdata/caddie-backend:development
    container_name: caddie_app
    env_file:
      - 'docker-django.env'
    restart: always
    ports:
      - 8112:8000
    networks:
      - db_net
      - redis_net
      - caddie
    depends_on:
      - db
      - redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: postgres
    restart: always
    hostname: db
    networks:
      - db_net
    volumes:
      - caddie_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=caddie
      - POSTGRES_USER=caddie
      - POSTGRES_PASSWORD=placeholder
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"
  redis:
    image: redis
    restart: always
    command: ["redis-server"]
    hostname: redis
    networks:
      - redis_net

networks:
  db_net:
  redis_net:
  caddie:

volumes:
  caddie_postgres_data:
